### ISSUE TITLE
Timeline / normalization Issue

### ISSUE THREAD

**Issue by PiMaV** [CodeSchmiedeHGW/BLITZ#24]
With subtract mean"range" in "selection" mode (the "aqua" checkbox):
(Checked with v1.1.0)

- when moving the blue box, mean is not updated. Have to uncheck / check the "aqua"checkbox, then its updated.
- When blue box is active: left and right click in timeline do nothing
- entering digits in the second range box alters numbers in the first

**Comment by irkri** [comment]
For the three problems:

- I cannot replicate that. You shouldn't be able to change the range if a normalization is already applied.
- This is intended. Uncheck the blue box if necessary. But only this way we can ensure that a left button click moves the blue box.
- I think this only happens if you enter invalid combinations (like a larger number as the starting point than the end point).

The last few commits might have fixed problems here. New testing is required.

**Comment by irkri** [comment]
1.) should now be working.
I need a more detailed problem description for 3).

**Comment by PiMaV** [comment]
Works OKish

**Comment by PiMaV** [comment]
Issue 3. is still there...

Trying to describe it again:

Its conntected to the "spinbox_norm_range_start" and end

Reproduce like this:
- Drag & drop a Dataset
- go to "time", click in the norm_range_start box and set it to i.e. 5 and hit "enter"
- click into the end box and type "1" (because we want to type "10")
- this sets the start to 1 and the end to 5

I guess this is due to some false type check for each number WHILE typing instead of chekcing once we are done...

**Comment by irkri** [comment]
Ah ... I did not understand the problem before. Should be fixed now. It was just four keywords I needed to change for the exact reason you mentioned.

**Comment by PiMaV** [comment]
tested. Worked
